name: UI Tests

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run UI-tests via docker-compose
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          docker-compose up --exit-code-from regression || true

      - name: Copy history from gh-pages to allure-results
        run: |
          sudo mkdir -p allure-results/history
          if [ -d "${GITHUB_WORKSPACE}/.github/gh-pages/history/" ]; then
            sudo cp -R ${GITHUB_WORKSPACE}/.github/gh-pages/history/* allure-results/history/
          else
            echo "Directory ${GITHUB_WORKSPACE}/.github/gh-pages/history/ does not exist. Creating it."
            sudo mkdir -p ${GITHUB_WORKSPACE}/.github/gh-pages/history/
          fi

      - name: Generate Allure report
        run: |
          sudo docker-compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Update Allure history
        run: |
          if [ -d "allure-report/history/" ]; then
            sudo cp -R allure-report/history/* ${GITHUB_WORKSPACE}/.github/gh-pages/history/
          else
            echo "Directory allure-report/history/ does not exist. Skipping copy."
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
